### ISSUE TITLE
TODO: allot meeting rooms, coordinate participant metadata

### ISSUE THREAD

**Issue by esskayesss** [contra-kvh/samklaang-be#6]
- [ ] provision meeting rooms
  - [x] #9
  - [ ] resolve meeting links with rooms
- [ ] manage access tokens and overall access control
- [ ] implement participant entities
- [ ] manage participant metadata

the result should be a functioning basic meeting room which accepts and propagates participant metadata. no specific meeting controls as of yet, that is for a later issue.
